'use client';
import { useEffect, useState } from 'react';
import { CareerOSShell, Badge, Button, Card, PageHeader } from '@/components/CareerOSShell';
import { apiClient } from '@/lib/api/client';

const nav=[['performance','Profile performance'],['personal','Personal details & professional identity'],['resume','Resume & career positioning'],['employment','Employment history'],['education','Education'],['certifications','Certifications & credentials'],['skills','IT skills & key skills'],['preferences','Career profile & preferences'],['sources','Profile sources & next actions']];
const split=(v:string)=>v.split(',').map(x=>x.trim()).filter(Boolean);
const Input=({label,value,onChange,type='text',placeholder=''}:{label:string;value:any;onChange:(v:string)=>void;type?:string;placeholder?:string})=><label className="block"><span className="text-xs font-semibold text-muted-foreground">{label}</span><input className="careeros-input mt-1.5" type={type} value={value??''} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label>;
const Area=({label,value,onChange}:{label:string;value:any;onChange:(v:string)=>void})=><label className="block"><span className="text-xs font-semibold text-muted-foreground">{label}</span><textarea className="careeros-input mt-1.5" rows={5} value={value??''} onChange={e=>onChange(e.target.value)}/></label>;

export default function ProfileSetup(){
 const [data,setData]=useState<any>(null);const [busy,setBusy]=useState('');const [msg,setMsg]=useState('');const [error,setError]=useState('');
 const [personal,setPersonal]=useState<any>({});const [exp,setExp]=useState<any>({company:'',title:'',location:'',start_date:'',end_date:'',is_current:false,responsibilities:'',achievements:''});const [edu,setEdu]=useState<any>({institution:'',degree:'',field_of_study:'',start_date:'',end_date:'',is_current:false,grade:''});const [cert,setCert]=useState<any>({name:'',issuer:'',issue_date:'',expiry_date:'',credential_reference:'',credential_url:''});const [skill,setSkill]=useState<any>({name:'',category:'IT / Technical',proficiency:'Intermediate',years_experience:''});
 const load=async()=>{try{const d=await apiClient.identityOverview();setData(d);const p=d.profile||{};setPersonal({full_name:p.full_name||'',location:p.location||'',title:p.title||'',summary:p.summary||'',primary_email:p.primary_email||'',primary_phone:p.primary_phone||'',linkedin_url:p.linkedin_url||'',years_experience:p.years_experience??'',seniority:p.seniority||'',industries:(p.industries||[]).join(', '),target_roles:(p.work_preferences?.target_roles||[]).join(', '),preferred_locations:(p.work_preferences?.preferred_locations||[]).join(', '),work_arrangement:p.work_preferences?.work_arrangement||p.work_preferences?.remote_preference||'',willing_to_relocate:String(p.work_preferences?.willing_to_relocate??'')})}catch(e:any){setError(e.message||'Unable to load Profile Setup')}};
 useEffect(()=>{void load()},[]);
 const savePersonal=async(e:any)=>{e.preventDefault();setBusy('personal');setMsg('');try{await apiClient.put('/api/v1/profile/',{full_name:personal.full_name,location:personal.location,title:personal.title,summary:personal.summary,primary_email:personal.primary_email,primary_phone:personal.primary_phone,linkedin_url:personal.linkedin_url,years_experience:personal.years_experience===''?null:Number(personal.years_experience),seniority:personal.seniority,industries:split(personal.industries),work_preferences:{target_roles:split(personal.target_roles),preferred_locations:split(personal.preferred_locations),work_arrangement:personal.work_arrangement,willing_to_relocate:personal.willing_to_relocate==='true'}});setMsg('Professional identity and career preferences saved.');await load()}catch(e:any){setMsg(e.message)}finally{setBusy('')}};
 const add=async(kind:string,e:any)=>{e.preventDefault();setBusy(kind);setMsg('');try{if(kind==='employment')await apiClient.post('/api/v1/profile/experiences',{...exp,candidate_id:data.profile.id,responsibilities:split(exp.responsibilities),achievements:split(exp.achievements),start_date:exp.start_date||null,end_date:exp.is_current?null:(exp.end_date||null)});if(kind==='education')await apiClient.post('/api/v1/profile/educations',{...edu,candidate_id:data.profile.id,start_date:edu.start_date||null,end_date:edu.is_current?null:(edu.end_date||null)});if(kind==='certifications')await apiClient.post('/api/v1/profile/certifications',{...cert,candidate_id:data.profile.id,issue_date:cert.issue_date||null,expiry_date:cert.expiry_date||null});if(kind==='skills')await apiClient.post('/api/v1/profile/skills',{...skill,candidate_id:data.profile.id,years_experience:skill.years_experience===''?null:Number(skill.years_experience)});setMsg(`${kind[0].toUpperCase()+kind.slice(1)} added to your professional identity.`);await load()}catch(e:any){setMsg(e.message)}finally{setBusy('')}};
 if(error)return <CareerOSShell><div className="rounded-2xl border border-red-500/30 bg-red-500/10 p-5 text-sm text-red-500">{error}</div></CareerOSShell>;
 if(!data)return <CareerOSShell><div className="grid min-h-[60vh] place-items-center text-sm text-muted-foreground">Loading Profile Setup…</div></CareerOSShell>;
 const p=data.profile||{};const navValue=(key:string)=>data.section_navigation?.[key];
 return <CareerOSShell><PageHeader eyebrow="Professional Identity" title="Profile Setup" description="Your editable professional identity workspace. CareerOS extracts what it can from your documents; use this area to confirm, correct or add information that documents cannot safely establish." action={<Badge tone="blue">{Math.round(Number(p.completeness_score)||0)}% complete</Badge>}/>
 {msg&&<div className="mb-5 rounded-xl border bg-card px-4 py-3 text-sm">{msg}</div>}
 <div className="grid gap-5 xl:grid-cols-[230px_minmax(0,1fr)]"><aside className="h-fit rounded-2xl border bg-card p-2 xl:sticky xl:top-28"><p className="px-3 py-2 text-[10px] font-bold uppercase tracking-[.16em] text-muted-foreground">Profile setup index</p>{nav.map(([id,label])=>{const v=navValue(id);return <a key={id} href={`#${id}`} className="flex items-center justify-between gap-2 rounded-xl px-3 py-2.5 text-left text-xs font-semibold text-muted-foreground hover:bg-muted hover:text-foreground"><span>{label}</span>{v&&<span className="h-1.5 w-1.5 rounded-full bg-primary"/>}</a>})}</aside>
 <div className="space-y-5">
  <section id="performance" className="scroll-mt-32"><Card title="Profile performance"><div className="grid gap-3 sm:grid-cols-4">{[['Completeness',data.intelligence?.profile_completeness],['Evidence coverage',data.intelligence?.evidence_coverage],['Data confidence',data.intelligence?.data_confidence],['Persona readiness',data.intelligence?.persona_readiness]].map(([a,b])=><div key={String(a)} className="rounded-xl border bg-background/30 p-4"><p className="text-xs text-muted-foreground">{a}</p><p className="mt-1 text-2xl font-bold">{Math.round(Number(b)||0)}%</p></div>)}</div><p className="mt-3 text-xs text-muted-foreground">These indicators are intentionally separate: they measure completeness, evidence, extraction confidence and persona readiness.</p></Card></section>
  <section id="personal" className="scroll-mt-32"><Card title="Personal details & professional identity"><form onSubmit={savePersonal} className="grid gap-4 md:grid-cols-2"><Input label="Professional name" value={personal.full_name} onChange={v=>setPersonal({...personal,full_name:v})}/><Input label="Professional headline" value={personal.title} onChange={v=>setPersonal({...personal,title:v})} placeholder="Role / leadership positioning"/><Input label="Location" value={personal.location} onChange={v=>setPersonal({...personal,location:v})}/><Input label="Primary email" value={personal.primary_email} onChange={v=>setPersonal({...personal,primary_email:v})}/><Input label="Phone" value={personal.primary_phone} onChange={v=>setPersonal({...personal,primary_phone:v})}/><Input label="LinkedIn URL" value={personal.linkedin_url} onChange={v=>setPersonal({...personal,linkedin_url:v})}/><Input label="Years of experience" type="number" value={personal.years_experience} onChange={v=>setPersonal({...personal,years_experience:v})}/><Input label="Career level" value={personal.seniority} onChange={v=>setPersonal({...personal,seniority:v})}/><Input label="Target roles" value={personal.target_roles} onChange={v=>setPersonal({...personal,target_roles:v})} placeholder="e.g. Cloud Architect, Technology Director"/><Input label="Preferred work locations" value={personal.preferred_locations} onChange={v=>setPersonal({...personal,preferred_locations:v})} placeholder="Cities or countries; comma separated"/><label className="block"><span className="text-xs font-semibold text-muted-foreground">Work arrangement</span><select className="careeros-input mt-1.5" value={personal.work_arrangement||''} onChange={e=>setPersonal({...personal,work_arrangement:e.target.value})}><option value="">Flexible / not specified</option><option>On-site</option><option>Hybrid</option><option>Remote within my country</option><option>Remote internationally</option><option>Flexible / any</option></select></label><label className="flex items-center gap-2 pt-6 text-sm"><input type="checkbox" checked={personal.willing_to_relocate==='true'} onChange={e=>setPersonal({...personal,willing_to_relocate:String(e.target.checked)})}/> Willing to relocate</label><div className="md:col-span-2"><Area label="Professional summary" value={personal.summary} onChange={v=>setPersonal({...personal,summary:v})}/></div><div className="md:col-span-2 flex justify-end"><Button disabled={busy==='personal'}>{busy==='personal'?'Saving…':'Save professional identity & preferences'}</Button></div></form></Card></section>
  <section id="resume" className="scroll-mt-32"><Card title="Resume & career positioning"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold">{data.documents?.filter((x:any)=>x.category==='cv').length||0} CV versions contributing</p><p className="mt-1 text-sm text-muted-foreground">Upload multiple CVs. CareerOS merges their evidence into one Career Vault instead of creating separate profiles.</p></div><a href="/documents#cv" className="rounded-xl bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground">Add CVs</a></div></Card></section>
  <section id="employment" className="scroll-mt-32"><Card title="Employment history"><div className="space-y-3">{(data.experiences||[]).map((x:any)=><div key={x.id} className="rounded-xl border p-4"><p className="font-semibold">{x.title} · {x.company}</p><p className="mt-1 text-xs text-muted-foreground">{String(x.start_date||'').slice(0,10)} — {x.is_current?'Present':String(x.end_date||'').slice(0,10)||'Date not recorded'}</p></div>)}<form onSubmit={e=>add('employment',e)} className="grid gap-3 border-t pt-4 md:grid-cols-2"><Input label="Employer" value={exp.company} onChange={v=>setExp({...exp,company:v})}/><Input label="Role" value={exp.title} onChange={v=>setExp({...exp,title:v})}/><Input label="Location" value={exp.location} onChange={v=>setExp({...exp,location:v})}/><Input label="Start date" type="date" value={exp.start_date} onChange={v=>setExp({...exp,start_date:v})}/><Input label="End date" type="date" value={exp.end_date} onChange={v=>setExp({...exp,end_date:v})}/><label className="flex items-center gap-2 pt-6 text-sm"><input type="checkbox" checked={exp.is_current} onChange={e=>setExp({...exp,is_current:e.target.checked})}/> Current role</label><Area label="Responsibilities (comma separated)" value={exp.responsibilities} onChange={v=>setExp({...exp,responsibilities:v})}/><Area label="Achievements (comma separated)" value={exp.achievements} onChange={v=>setExp({...exp,achievements:v})}/><div className="md:col-span-2"><Button disabled={busy==='employment'}>{busy==='employment'?'Adding…':'Add employment record'}</Button></div></form></div></Card></section>
  <section id="education" className="scroll-mt-32"><Card title="Education"><div className="space-y-3">{(data.educations||[]).map((x:any)=><div key={x.id} className="rounded-xl border p-4"><p className="font-semibold">{x.degree}</p><p className="mt-1 text-sm text-muted-foreground">{x.institution}{x.field_of_study?` · ${x.field_of_study}`:''}</p></div>)}<form onSubmit={e=>add('education',e)} className="grid gap-3 border-t pt-4 md:grid-cols-2"><Input label="Institution / university" value={edu.institution} onChange={v=>setEdu({...edu,institution:v})}/><Input label="Degree / qualification" value={edu.degree} onChange={v=>setEdu({...edu,degree:v})}/><Input label="Field of study" value={edu.field_of_study} onChange={v=>setEdu({...edu,field_of_study:v})}/><Input label="Graduation / end date" type="date" value={edu.end_date} onChange={v=>setEdu({...edu,end_date:v})}/><Input label="Grade / GPA (optional)" value={edu.grade} onChange={v=>setEdu({...edu,grade:v})}/><div className="md:col-span-2"><Button disabled={busy==='education'}>{busy==='education'?'Adding…':'Add education record'}</Button></div></form></div></Card></section>
  <section id="certifications" className="scroll-mt-32"><Card title="Certifications & credentials"><div className="space-y-3">{(data.certifications||[]).map((x:any)=><div key={x.id} className="rounded-xl border p-4"><p className="font-semibold">{x.name}</p><p className="mt-1 text-sm text-muted-foreground">{x.issuer||'Issuer not recorded'}{x.credential_reference?` · ${x.credential_reference}`:''}</p></div>)}<form onSubmit={e=>add('certifications',e)} className="grid gap-3 border-t pt-4 md:grid-cols-2"><Input label="Certification name" value={cert.name} onChange={v=>setCert({...cert,name:v})}/><Input label="Issuing organization" value={cert.issuer} onChange={v=>setCert({...cert,issuer:v})}/><Input label="Issue date" type="date" value={cert.issue_date} onChange={v=>setCert({...cert,issue_date:v})}/><Input label="Expiry date" type="date" value={cert.expiry_date} onChange={v=>setCert({...cert,expiry_date:v})}/><Input label="Credential ID" value={cert.credential_reference} onChange={v=>setCert({...cert,credential_reference:v})}/><Input label="Credential URL" value={cert.credential_url} onChange={v=>setCert({...cert,credential_url:v})}/><div className="md:col-span-2"><Button disabled={busy==='certifications'}>{busy==='certifications'?'Adding…':'Add certification'}</Button></div></form></div></Card></section>
  <section id="skills" className="scroll-mt-32"><Card title="IT skills & key skills"><div className="flex flex-wrap gap-2">{(data.skills||[]).map((x:any)=><Badge key={x.id}>{x.name}</Badge>)}</div><form onSubmit={e=>add('skills',e)} className="mt-4 grid gap-3 border-t pt-4 md:grid-cols-2"><Input label="Skill / capability" value={skill.name} onChange={v=>setSkill({...skill,name:v})}/><Input label="Category" value={skill.category} onChange={v=>setSkill({...skill,category:v})}/><Input label="Proficiency" value={skill.proficiency} onChange={v=>setSkill({...skill,proficiency:v})}/><Input label="Years using skill" type="number" value={skill.years_experience} onChange={v=>setSkill({...skill,years_experience:v})}/><div className="md:col-span-2"><Button disabled={busy==='skills'}>{busy==='skills'?'Adding…':'Add skill'}</Button></div></form></Card></section>
  <section id="preferences" className="scroll-mt-32"><Card title="Career profile & preferences"><div className="grid gap-3 md:grid-cols-3"><div className="rounded-xl border p-4"><p className="text-xs text-muted-foreground">Target roles</p><p className="mt-1 text-sm font-semibold">{personal.target_roles||'Open / not specified'}</p></div><div className="rounded-xl border p-4"><p className="text-xs text-muted-foreground">Preferred work locations</p><p className="mt-1 text-sm font-semibold">{personal.preferred_locations||'Open / not specified'}</p></div><div className="rounded-xl border p-4"><p className="text-xs text-muted-foreground">Work arrangement</p><p className="mt-1 text-sm font-semibold">{personal.work_arrangement||'Flexible / not specified'}</p></div></div><p className="mt-3 text-xs text-muted-foreground">These are your choices, not facts inferred from documents. They remain optional and can be changed at any time.</p></Card></section>
  <section id="sources" className="scroll-mt-32"><Card title="Profile sources & next actions"><div className="grid gap-3 sm:grid-cols-3">{(data.documents||[]).slice(0,6).map((x:any)=><a key={x.id} href="/evidence-library" className="rounded-xl border p-3 hover:bg-muted/50"><p className="truncate text-sm font-semibold">{x.user_label||x.original_filename}</p><p className="mt-1 text-xs text-muted-foreground">{x.detected_type||'Document'} · {x.verification_status}</p></a>)}<a href="/evidence-library" className="rounded-xl border border-dashed p-3 hover:bg-muted/50"><p className="text-sm font-semibold">Add supporting evidence</p><p className="mt-1 text-xs text-muted-foreground">Strengthen facts without retyping them.</p></a></div></Card></section>
 </div></div></CareerOSShell>;
}
