'use client';

import { useEffect, useRef, useState } from 'react';

export default function DocumentScanner({ onCapture }:{onCapture:(file:File)=>void}) {
  const videoRef=useRef<HTMLVideoElement>(null); const streamRef=useRef<MediaStream|null>(null); const [open,setOpen]=useState(false); const [error,setError]=useState(''); const [supported,setSupported]=useState(true);
  useEffect(()=>()=>{streamRef.current?.getTracks().forEach(t=>t.stop())},[]);
  const start=async()=>{setError('');setOpen(true);if(!window.isSecureContext||!navigator.mediaDevices?.getUserMedia){setSupported(false);return}try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});streamRef.current=stream;if(videoRef.current)videoRef.current.srcObject=stream}catch(e:any){setSupported(false);setError(e?.message||'Camera permission was not granted.')}};
  const close=()=>{streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;setOpen(false)};
  const capture=()=>{const video=videoRef.current;if(!video||!video.videoWidth)return;const canvas=document.createElement('canvas');canvas.width=video.videoWidth;canvas.height=video.videoHeight;canvas.getContext('2d')?.drawImage(video,0,0);canvas.toBlob(blob=>{if(blob){onCapture(new File([blob],`CareerOS-scan-${new Date().toISOString().slice(0,19).replace(/[:T]/g,'-')}.jpg`,{type:'image/jpeg'}));close()}},'image/jpeg',.92)};
  return <>{<button type="button" onClick={start} className="rounded-lg border px-4 py-2 text-sm font-semibold hover:bg-muted">Scan with camera</button>}{open&&<div className="fixed inset-0 z-[60] grid place-items-center bg-black/70 p-4"><div className="w-full max-w-lg rounded-2xl border bg-card p-4 shadow-2xl"><div className="flex items-center justify-between"><div><p className="font-semibold">CareerOS document scanner</p><p className="text-xs text-muted-foreground">Frame the document and capture one page.</p></div><button onClick={close} className="grid h-9 w-9 place-items-center rounded-lg border">×</button></div>{supported?<div className="mt-4 overflow-hidden rounded-xl bg-black"><video ref={videoRef} autoPlay playsInline className="aspect-[4/3] w-full object-cover"/></div>:<div className="mt-4 rounded-xl border border-amber-500/30 bg-amber-500/10 p-4 text-sm"><p className="font-semibold">Browser camera access is unavailable here.</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Camera APIs require a secure context. If you opened CareerOS from another device using plain HTTP, use the device camera/file option below or serve the site over HTTPS.</p>{error&&<p className="mt-2 text-xs text-amber-700 dark:text-amber-300">{error}</p>}<input type="file" accept="image/*" capture="environment" className="mt-3 block w-full text-sm" onChange={e=>{const f=e.target.files?.[0];if(f){onCapture(f);close()}}}/></div>}{supported&&<div className="mt-4 flex justify-end gap-2"><button onClick={close} className="rounded-lg border px-4 py-2.5 text-sm font-semibold">Cancel</button><button onClick={capture} className="rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground">Capture page</button></div>}</div></div>}</>;
}
