'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { CareerOSShell, Badge, Button, Card, PageHeader } from '@/components/CareerOSShell';
import { apiClient } from '@/lib/api/client';

function OpenEvidence({ id, label = 'Open evidence' }: { id: string; label?: string }) {
  const open = async () => { try { const blob = await apiClient.openDocumentContent(id); const url = URL.createObjectURL(blob); window.open(url, '_blank', 'noopener,noreferrer'); setTimeout(() => URL.revokeObjectURL(url), 60000); } catch (e: any) { alert(e?.message || 'Unable to open document'); } };
  return <button onClick={open} className="rounded-lg border px-2.5 py-1.5 text-xs font-semibold text-primary hover:bg-primary/5">{label}</button>;
}
const date=(v:any)=>v?String(v).slice(0,10):'';
const tone=(s:string)=>s==='complete'?'good':s==='needs_review'?'warn':'blue';

export default function ProfilePage(){
 const [data,setData]=useState<any>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(true);
 useEffect(()=>{apiClient.identityOverview().then(setData).catch(e=>setError(e.message||'Unable to load Career Passport')).finally(()=>setLoading(false))},[]);
 if(loading)return <CareerOSShell><div className="grid min-h-[60vh] place-items-center text-sm text-muted-foreground">Building your Career Passport…</div></CareerOSShell>;
 if(error)return <CareerOSShell><div className="rounded-2xl border border-red-500/30 bg-red-500/10 p-5 text-sm text-red-500">{error}</div></CareerOSShell>;
 const p=data?.profile||{};const intelligence=data?.intelligence||{};const sections=data?.section_navigation||{};
 return <CareerOSShell><PageHeader eyebrow="Professional Identity" title="Career Passport" description="Your evidence-backed professional identity. Editing and confirmation belong in Profile Setup; this page is your professional view." action={<Link href="/profile/setup"><Button>Edit / Complete Profile</Button></Link>}/>
 <div className="grid gap-5 xl:grid-cols-[minmax(0,1.5fr)_minmax(300px,.7fr)]"><div className="space-y-5">
  <Card className="techno-glow"><div className="flex flex-col gap-5 sm:flex-row sm:items-center"><div className="grid h-24 w-24 shrink-0 place-items-center rounded-3xl bg-primary/10 text-3xl font-bold text-primary ring-1 ring-primary/20">{(p.full_name||'A').slice(0,1).toUpperCase()}</div><div className="min-w-0"><p className="text-xs font-bold uppercase tracking-[.16em] text-primary">Professional identity</p><h2 className="mt-1 text-3xl font-bold tracking-tight">{p.full_name||'Complete your name'}</h2><p className="mt-1 text-base text-muted-foreground">{p.title||'Professional headline pending'}</p><div className="mt-3 flex flex-wrap gap-2">{p.location&&<Badge tone="blue">{p.location}</Badge>}{p.seniority&&<Badge>{p.seniority}</Badge>}{p.primary_email&&<Badge>{p.primary_email}</Badge>}</div></div></div>{p.summary&&<p className="mt-6 max-w-4xl text-sm leading-7 text-muted-foreground">{p.summary}</p>}</Card>
  <Card title="Career intelligence"><div className="grid gap-3 sm:grid-cols-4">{[['Profile completeness',intelligence.profile_completeness],['Evidence coverage',intelligence.evidence_coverage],['Data confidence',intelligence.data_confidence],['Persona readiness',intelligence.persona_readiness]].map(([label,value])=><div key={String(label)} className="rounded-xl border bg-background/30 p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-bold">{Math.round(Number(value)||0)}%</p></div>)}</div><p className="mt-4 text-xs text-muted-foreground">These are separate indicators—not a fabricated single “AI score”.</p></Card>
  <Card title="Professional timeline"><div className="space-y-4">{(data.experiences||[]).length?data.experiences.map((x:any)=><div key={x.id} className="rounded-xl border p-4"><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><h3 className="font-semibold">{x.title}</h3><p className="mt-1 text-sm text-muted-foreground">{x.company}{x.location?` · ${x.location}`:''}</p><p className="mt-1 text-xs text-muted-foreground">{date(x.start_date)||'Date not recorded'} — {x.is_current?'Present':date(x.end_date)||'End date not recorded'}</p></div><div className="flex flex-wrap gap-2">{x.evidence?.length?x.evidence.slice(0,3).map((e:any)=><OpenEvidence key={e.document_id} id={e.document_id} label={e.filename||'Evidence'}/>):<Badge>Evidence pending</Badge>}</div></div>{x.achievements?.length>0&&<ul className="mt-3 list-disc space-y-1 pl-5 text-sm text-muted-foreground">{x.achievements.slice(0,3).map((a:string,i:number)=><li key={i}>{a}</li>)}</ul>}</div>):<p className="text-sm text-muted-foreground">Employment history will appear after your CV or employment documents are processed.</p>}</div></Card>
  <div className="grid gap-5 lg:grid-cols-2"><Card title="Education"><div className="space-y-3">{(data.educations||[]).length?data.educations.map((x:any)=><div key={x.id} className="rounded-xl border p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold">{x.degree}</h3><p className="mt-1 text-sm text-muted-foreground">{x.institution}</p>{x.field_of_study&&<p className="mt-1 text-xs text-muted-foreground">{x.field_of_study}</p>}</div>{x.evidence?.length?<OpenEvidence id={x.evidence[0].document_id} label="Evidence"/>:<Badge>Evidence pending</Badge>}</div></div>):<p className="text-sm text-muted-foreground">No education record has been safely extracted yet.</p>}</div></Card>
  <Card title="Certifications & credentials"><div className="space-y-3">{(data.certifications||[]).length?data.certifications.map((x:any)=><div key={x.id} className="rounded-xl border p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold">{x.name}</h3><p className="mt-1 text-sm text-muted-foreground">{x.issuer||'Issuer not recorded'}</p>{x.credential_reference&&<p className="mt-1 text-xs text-muted-foreground">Credential: {x.credential_reference}</p>}</div>{x.evidence?.length?<OpenEvidence id={x.evidence[0].document_id} label="Evidence"/>:<Badge>CV reported</Badge>}</div></div>):<p className="text-sm text-muted-foreground">No certification has been confidently identified. Add a CV certification section or upload the certificate itself.</p>}</div></Card></div>
  <Card title="Core capabilities"><div className="flex flex-wrap gap-2">{(data.skills||[]).length?data.skills.map((x:any)=><span key={x.id} className="rounded-full border bg-background/30 px-3 py-1.5 text-xs font-medium">{x.name}{x.category&&<span className="ml-1 text-muted-foreground">· {x.category}</span>}</span>):<p className="text-sm text-muted-foreground">Skills are derived from the CV Skills/Technical Skills sections—not from certification or education text.</p>}</div></Card>
 </div><aside className="space-y-5 xl:sticky xl:top-28 xl:self-start">
  <Card title="Profile sections"><div className="space-y-2">{Object.entries(sections).map(([key,value]:any)=><a key={key} href={`/profile/setup#${key}`} className="flex items-center justify-between rounded-xl border px-3 py-2.5 hover:bg-muted/50"><span className="text-sm">{value.label}</span><Badge tone={tone(value.status)}>{String(value.status).replace('_',' ')}</Badge></a>)}</div></Card>
  <Card title="Evidence coverage"><div className="space-y-2 text-sm"><div className="flex justify-between"><span className="text-muted-foreground">Career documents</span><strong>{data.documents?.length||0}</strong></div><div className="flex justify-between"><span className="text-muted-foreground">Evidence links</span><strong>{data.documents?.reduce((n:number,d:any)=>n+Number(d.linked_fact_count||0),0)||0}</strong></div><div className="flex justify-between"><span className="text-muted-foreground">CV sources</span><strong>{data.documents?.filter((d:any)=>d.category==='cv').length||0}</strong></div></div><Link href="/evidence-library" className="mt-4 block text-sm font-semibold text-primary">Open Evidence Library →</Link></Card>
  <Card title="Career personas"><div className="space-y-3">{(data.personas||[]).filter((x:any)=>x.is_active).map((x:any)=><div key={x.id} className="rounded-xl border p-3"><p className="font-semibold">{x.name}</p><p className="mt-1 text-xs text-muted-foreground">{x.positioning||x.description}</p></div>)}{data.persona_suggestions?.length?<div className="rounded-xl border border-primary/20 bg-primary/5 p-3"><p className="text-sm font-semibold">CareerOS found {data.persona_suggestions.length} positioning possibilities.</p><p className="mt-1 text-xs text-muted-foreground">They use the same Career Vault facts; review before activation.</p><Link href="/personas" className="mt-2 inline-block text-xs font-semibold text-primary">Review suggestions →</Link></div>:null}</div></Card>
  <Card title="Next best actions"><div className="space-y-3">{(data.next_actions||[]).map((x:any)=><Link key={x.key} href={x.key.includes('evidence')?'/evidence-library':x.key==='review_personas'?'/personas':'/profile/setup'} className="block rounded-xl border p-3 hover:bg-muted/50"><p className="text-sm font-semibold">{x.label}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{x.detail}</p></Link>)}{!(data.next_actions||[]).length&&<p className="text-sm text-muted-foreground">Your identity workspace is in good shape. New evidence will surface the next useful action.</p>}</div></Card>
 </aside></div></CareerOSShell>;
}
