'use client';

import { useEffect, useMemo, useState } from 'react';
import { CareerOSShell, Badge, Button, Card, PageHeader } from '@/components/CareerOSShell';
import { apiClient } from '@/lib/api/client';

const categories=[['all','All'],['cv','CV / Resume'],['education','Education'],['certification','Certification'],['employment','Employment'],['achievement','Awards'],['project','Projects'],['reference','References'],['other','Other']];
const fmt=(v:any)=>v?String(v).slice(0,10):'—';

export default function EvidenceLibrary(){
 const [data,setData]=useState<any>({documents:[]});const [category,setCategory]=useState('all');const [verification,setVerification]=useState('all');const [search,setSearch]=useState('');const [selected,setSelected]=useState<any>(null);const [error,setError]=useState('');const [busy,setBusy]=useState('');
 const load=async()=>{try{setData(await apiClient.evidenceLibrary())}catch(e:any){setError(e.message||'Unable to load Evidence Library')}};
 useEffect(()=>{void load()},[]);
 const filterClient=useMemo(()=> (data.documents||[]).filter((d:any)=>(category==='all'||d.category===category)&&(verification==='all'||d.verification_status===verification)&&(!search||`${d.user_label||d.filename||''} ${d.detected_type||''} ${d.issuer||''}`.toLowerCase().includes(search.toLowerCase()))),[data,category,verification,search]);
 const open=async(id:string)=>{try{setSelected(await apiClient.documentDetail(id))}catch(e:any){setError(e.message)}};
 const openFile=async(id:string)=>{try{const blob=await apiClient.openDocumentContent(id);const url=URL.createObjectURL(blob);window.open(url,'_blank','noopener,noreferrer');setTimeout(()=>URL.revokeObjectURL(url),60000)}catch(e:any){setError(e.message)}};
 const aiEnrich=async(id:string)=>{setBusy(id);setError('');try{await apiClient.aiEnrichDocument(id);await load();if(selected?.id===id)setSelected(await apiClient.documentDetail(id))}catch(e:any){setError(e.message||'AI document analysis failed')}finally{setBusy('')}};
 return <CareerOSShell><PageHeader eyebrow="Professional Identity" title="Evidence Library" description="A simple AI-organized evidence vault. CareerOS identifies what a document proves, gives it a meaningful name and links it to the relevant profile facts." action={<a href="/documents#evidence" className="rounded-xl bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground">Add evidence</a>}/>
 {error&&<div className="mb-4 rounded-xl border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-500">{error}</div>}
 <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_340px]"><div className="space-y-5">
  <Card><div className="grid gap-3 lg:grid-cols-[minmax(0,1fr)_180px_180px]"><input className="careeros-input" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search evidence or issuer…"/><select className="careeros-input" value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select className="careeros-input" value={verification} onChange={e=>setVerification(e.target.value)}><option value="all">All states</option><option value="reported">Reported</option><option value="verified">Verified</option><option value="needs_confirmation">Needs confirmation</option><option value="conflicting">Conflicting</option></select></div></Card>
  <Card title={`Evidence · ${filterClient.length}`}><div className="overflow-x-auto"><table className="min-w-[760px] w-full text-left text-sm"><thead><tr className="border-b text-xs text-muted-foreground"><th className="px-3 py-3">Evidence</th><th className="px-3 py-3">Type</th><th className="px-3 py-3">Issuer</th><th className="px-3 py-3">Date</th><th className="px-3 py-3">State</th><th className="px-3 py-3">Confidence</th><th className="px-3 py-3">Links</th><th className="px-3 py-3">Actions</th></tr></thead><tbody>{filterClient.map((d:any)=><tr key={d.id} className="border-b last:border-0 hover:bg-muted/30"><td className="px-3 py-3"><button onClick={()=>void open(d.id)} className="max-w-[240px] text-left"><p className="truncate font-semibold text-primary">{d.user_label||d.filename||'Career evidence'}</p><p className="truncate text-xs text-muted-foreground">AI-organized document</p></button></td><td className="px-3 py-3"><Badge tone="blue">{String(d.detected_type||'other:unknown').replace(':',' · ')}</Badge></td><td className="px-3 py-3 text-xs">{d.issuer||'—'}</td><td className="px-3 py-3 text-xs">{fmt(d.issue_date||d.created_at)}</td><td className="px-3 py-3"><Badge tone={d.verification_status==='verified'?'good':d.verification_status==='conflicting'?'warn':'muted'}>{String(d.verification_status||'reported').replace('_',' ')}</Badge></td><td className="px-3 py-3 text-xs">{d.classification_confidence!=null?`${Math.round(Number(d.classification_confidence)*100)}%`:'—'}</td><td className="px-3 py-3 text-xs">{d.linked_fact_count||0}</td><td className="px-3 py-3"><div className="flex gap-2"><button onClick={()=>void openFile(d.id)} className="rounded-lg border px-2.5 py-1.5 text-xs font-semibold hover:bg-muted">Open</button><button disabled={busy===d.id} onClick={()=>void aiEnrich(d.id)} className="rounded-lg border px-2.5 py-1.5 text-xs font-semibold hover:bg-muted">{busy===d.id?'Analyzing…':'AI analyze'}</button></div></td></tr>)}</tbody></table></div>{!filterClient.length&&<div className="rounded-xl border border-dashed p-10 text-center"><p className="font-semibold">No evidence in this view</p><p className="mt-1 text-sm text-muted-foreground">Upload a professional document and CareerOS will understand and organize it.</p></div>}</Card>
 </div>
 <aside>{selected?<Card title="Evidence detail"><div className="space-y-4"><div><p className="text-xs text-muted-foreground">CareerOS name</p><p className="mt-1 font-semibold">{selected.user_label||selected.filename||'Career evidence'}</p></div><div className="grid grid-cols-2 gap-2"><div className="rounded-xl border p-3"><p className="text-[10px] text-muted-foreground">Detected type</p><p className="mt-1 text-sm font-semibold">{selected.detected_type||'Unknown'}</p></div><div className="rounded-xl border p-3"><p className="text-[10px] text-muted-foreground">Confidence</p><p className="mt-1 text-sm font-semibold">{selected.classification_confidence!=null?`${Math.round(selected.classification_confidence*100)}%`:'—'}</p></div></div><div><p className="text-xs text-muted-foreground">What this document contains</p><p className="mt-1 text-sm leading-6">{selected.classification_reason||'AI description pending.'}</p></div><div><p className="text-xs text-muted-foreground">Issuer / organization</p><p className="mt-1 text-sm">{selected.issuer||'Not detected'}</p></div><div><p className="text-xs text-muted-foreground">Linked profile facts</p><div className="mt-2 space-y-2">{(selected.linked_facts||[]).map((x:any,i:number)=><div key={i} className="rounded-xl border p-3"><p className="text-xs font-semibold">{x.fact_type}</p><p className="mt-1 text-xs text-muted-foreground">{x.excerpt||'Supports this profile fact'}</p></div>)}{!selected.linked_facts?.length&&<p className="text-xs text-muted-foreground">No profile fact matched yet.</p>}</div></div><div className="flex flex-wrap gap-2"><Button onClick={()=>void openFile(selected.id)}>Open document</Button><Button onClick={()=>void aiEnrich(selected.id)} disabled={busy===selected.id}>{busy===selected.id?'Analyzing…':'Analyze with AI'}</Button><button onClick={()=>setSelected(null)} className="rounded-xl border px-4 py-2.5 text-sm font-semibold hover:bg-muted">Close</button></div></div></Card>:<Card title="AI evidence vault"><p className="text-sm leading-6 text-muted-foreground">Upload a degree, certificate, employment letter, award or other professional record. CareerOS classifies it from content, extracts relevant metadata, gives it a useful name and links it to the matching profile fact.</p><div className="mt-4 space-y-2 text-xs"><p>• CV = reported source.</p><p>• Dedicated supporting document = stronger evidence.</p><p>• Uncertain matches stay in review.</p><p>• Missing evidence appears directly on the Profile.</p></div></Card>}</aside></div>
 </CareerOSShell>;
}
