'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { CareerOSShell, Card, PageHeader, Button, Badge } from '@/components/CareerOSShell';
import { apiClient } from '@/lib/api/client';

type DeveloperStatus = { tools?: string[]; developer_mode?: boolean; role?: string; email?: string };
type ResetResponse = { documents_removed?: number };

export default function DeveloperMode(){
 const [status,setStatus]=useState<DeveloperStatus|null>(null);const [msg,setMsg]=useState('');const [busy,setBusy]=useState(false);
 useEffect(()=>{apiClient.get<DeveloperStatus>('/api/v1/developer/status').then(setStatus).catch(e=>setMsg(e.message||'Developer access denied'))},[]);
 const reset=async()=>{if(!confirm('Reset your CareerOS test profile? This removes your uploaded career documents, parsed profile facts, persona suggestions/personas and email connector state for this account. Your login account is preserved.'))return;setBusy(true);try{const r=await apiClient.post<ResetResponse>('/api/v1/developer/reset-profile',{});setMsg(`Reset complete. ${r.documents_removed||0} documents removed; login preserved.`)}catch(e:any){setMsg(e.message)}finally{setBusy(false)}};
 if(!status)return <CareerOSShell><div className="grid min-h-[50vh] place-items-center text-sm text-muted-foreground">{msg||'Checking Developer Mode…'}</div></CareerOSShell>;
 return <CareerOSShell><PageHeader eyebrow="Project Control" title="Developer Mode" description="Controlled tools for repeating CV onboarding and identity testing. These actions are restricted to authorized developer accounts and never delete the login itself." action={<Badge tone="good">Authorized developer</Badge>}/><div className="grid gap-5 lg:grid-cols-[minmax(0,1.2fr)_minmax(300px,.8fr)]"><div className="space-y-5"><Card title="Reset my CareerOS test profile" className="techno-glow"><p className="text-sm leading-6 text-muted-foreground">Use this before a fresh onboarding test. It clears parsed profile data, uploaded career documents, evidence links, generated personas and email connector state for your own account only.</p><div className="mt-5"><Button onClick={reset} disabled={busy}>{busy?'Resetting…':'Reset my CareerOS test profile'}</Button></div></Card><Card title="Developer tools"><div className="grid gap-3 sm:grid-cols-2">{(status.tools||[]).map((x:string)=><div key={x} className="rounded-xl border p-3"><p className="text-sm font-semibold">{x.replaceAll('_',' ')}</p><p className="mt-1 text-xs text-muted-foreground">Available to this developer account.</p></div>)}</div></Card></div><aside className="space-y-5"><Card title="Safety boundary"><div className="space-y-2 text-sm text-muted-foreground"><p>• Scoped to the authenticated developer.</p><p>• Login account is preserved.</p><p>• Destructive reset is explicit and audit logged.</p><p>• OAuth tokens are never shown.</p><p>• Ordinary users receive HTTP 403.</p></div></Card><Card title="Repeat the onboarding journey"><ol className="list-decimal space-y-2 pl-5 text-sm text-muted-foreground"><li>Reset test profile.</li><li><Link className="text-primary font-semibold" href="/documents#cv">Upload CV #1</Link>.</li><li>Upload supporting certificates/degrees.</li><li>Review the Career Passport and Evidence Library.</li><li>Generate and review Personas.</li></ol></Card></aside></div>{msg&&<div className="mt-4 rounded-xl border bg-card p-3 text-sm">{msg}</div>}</CareerOSShell>;
}
