'use client';
import Link from 'next/link';
import { CareerOSShell, Card, PageHeader, Badge } from '@/components/CareerOSShell';

const milestones=[
 ['M02 Profile Foundation v1.1','Foundation checkpoint · 9bd4d80','baseline'],
 ['M02 Profile Repair v1.2','Navigation, shell and evidence reconciliation','complete'],
 ['M02 Profile Builder v1.3','Complete profile builder + OAuth/mobile/API UX fixes','active'],
 ['Professional Document Vault','Bulk files + folder + ZIP + OCR + provenance','active'],
 ['Global Job Discovery','Global search and source intelligence','next'],
 ['Live Interview Assistant','Real-time interview assistance workspace','later'],
];
const gates=['Pre-change backup branch created before v1.3 work','Existing authentication/session flow preserved','Vertical navigation is domain-level; horizontal navigation is contextual','Canonical CandidateProfile structures reused for M02 profile data','Original uploaded evidence remains authoritative','Runtime verification is required before promotion'];
export default function ProjectTracker(){return <CareerOSShell><PageHeader eyebrow="Project Control" title="CareerOS project tracker" description="The control plane for module sequencing, implementation status, verification gates and safe Git progression." action={<Link href="/roadmap" className="rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground">Open roadmap</Link>}/><div className="grid gap-4 md:grid-cols-4"><Card><p className="text-xs text-muted-foreground">Current milestone</p><p className="mt-2 text-lg font-bold">M02 Profile Builder</p><p className="text-xs text-primary">v1.3 · 2026-09-02</p></Card><Card><p className="text-xs text-muted-foreground">Pre-change backup</p><p className="mt-2 font-mono text-sm">backup/m02-profile-repair-v1.2-20260902-pre-profile-qa</p><Badge tone="good">Locked</Badge></Card><Card><p className="text-xs text-muted-foreground">Next product loop</p><p className="mt-2 text-lg font-bold">Profile → Jobs</p><p className="text-xs text-muted-foreground">after profile verification</p></Card><Card><p className="text-xs text-muted-foreground">Control status</p><p className="mt-2 text-lg font-bold">QA / Local Test</p><Badge tone="blue">Open</Badge></Card></div><div className="mt-5 grid gap-5 lg:grid-cols-[1.3fr_.7fr]"><Card title="Milestone board"><div className="space-y-3">{milestones.map(([name,detail,status])=><div key={name} className="flex flex-col gap-2 rounded-xl border p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold">{name}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></div><Badge tone={status==='active'?'blue':status==='complete'||status==='baseline'?'good':'muted'}>{status}</Badge></div>)}</div></Card><Card title="Engineering safety gates"><ul className="space-y-3 text-sm">{gates.map(g=><li key={g} className="flex gap-2"><span className="text-primary">✓</span><span>{g}</span></li>)}</ul><div className="mt-5 border-t pt-4"><p className="text-xs text-muted-foreground">Related control pages</p><div className="mt-2 flex flex-wrap gap-2"><Link href="/bug-tracker" className="text-xs font-semibold text-primary">Bug tracker →</Link><Link href="/roadmap" className="text-xs font-semibold text-primary">Roadmap →</Link></div></div></Card></div></CareerOSShell>}
