'use client';

import { useEffect, useState } from 'react';
import { CareerOSShell, Card, PageHeader, Button, Badge } from '@/components/CareerOSShell';
import { apiClient } from '@/lib/api/client';

export default function Personas(){
 const [data,setData]=useState<any>(null);const [suggestions,setSuggestions]=useState<any[]>([]);const [personas,setPersonas]=useState<any[]>([]);const [busy,setBusy]=useState('');const [msg,setMsg]=useState('');
 const load=async()=>{try{const d=await apiClient.identityOverview();setData(d);setSuggestions(d.persona_suggestions||[]);setPersonas(d.personas||[])}catch(e:any){setMsg(e.message||'Unable to load personas')}};
 useEffect(()=>{void load()},[]);
 const discover=async()=>{setBusy('discover');setMsg('');try{const created=await apiClient.generatePersonaSuggestions();if(!created.length)setMsg('CareerOS does not yet have enough evidence for a safe new persona. Add or confirm more career facts.');else setMsg(`CareerOS identified ${created.length} new positioning possibility${created.length===1?'':'ies'}.`);await load()}catch(e:any){setMsg(e.message)}finally{setBusy('')}};
 const activate=async(id:string)=>{setBusy(id);try{await apiClient.activatePersonaSuggestion(id);setMsg('Persona activated over the same Career Vault facts.');await load()}catch(e:any){setMsg(e.message)}finally{setBusy('')}};
 const manual=async()=>{const name=prompt('Persona name');if(!name)return;setBusy('manual');try{await apiClient.post('/api/v1/persona-builder/build',{name,target_titles:[name]});setMsg('Persona created as a draft.');await load()}catch(e:any){setMsg(e.message)}finally{setBusy('')}};
 return <CareerOSShell><PageHeader eyebrow="Professional Identity" title="Personas" description="Personas are positioning lenses over one evidence-backed career history. They can change how CareerOS presents you for a role without creating a second set of career facts." action={<div className="flex flex-wrap gap-2"><button onClick={discover} disabled={busy==='discover'} className="rounded-xl border bg-card px-4 py-2.5 text-sm font-semibold hover:bg-muted">{busy==='discover'?'Analyzing…':'Discover personas'}</button><Button onClick={manual} disabled={busy==='manual'}>{busy==='manual'?'Creating…':'Create manually'}</Button></div>}/>
 {msg&&<div className="mb-4 rounded-xl border bg-card px-4 py-3 text-sm">{msg}</div>}
 <div className="grid gap-5 xl:grid-cols-[minmax(0,1.35fr)_minmax(320px,.65fr)]"><div className="space-y-5">
  <Card title="Suggested positioning"><p className="mb-4 text-sm text-muted-foreground">Suggestions are generated from employment, skills, certifications, seniority and other Career Vault facts. Low-confidence possibilities are not silently activated.</p>{suggestions.length?<div className="grid gap-4 md:grid-cols-2">{suggestions.map((p:any)=><div key={p.id} className="rounded-2xl border bg-background/25 p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-primary">{p.role_family}</p><h2 className="mt-1 text-lg font-semibold">{p.name}</h2></div><Badge tone="blue">{Math.round((p.confidence||0)*100)}%</Badge></div><p className="mt-3 text-sm leading-6 text-muted-foreground">{p.positioning}</p><div className="mt-4 rounded-xl border bg-card/60 p-3"><p className="text-xs font-semibold">Why suggested</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{p.reason}</p></div>{p.missing_evidence?.length?<div className="mt-3"><p className="text-xs font-semibold">Could strengthen with</p><ul className="mt-1 list-disc pl-5 text-xs text-muted-foreground">{p.missing_evidence.map((x:string,i:number)=><li key={i}>{x}</li>)}</ul></div>:null}<div className="mt-4 flex justify-end"><Button disabled={busy===p.id} onClick={()=>void activate(p.id)}>{busy===p.id?'Activating…':'Activate persona'}</Button></div></div>)}</div>:<div className="rounded-xl border border-dashed p-8 text-center"><p className="font-semibold">No persona suggestions yet</p><p className="mt-1 text-sm text-muted-foreground">Upload CVs and supporting evidence first, then let CareerOS evaluate safe positioning possibilities.</p><Button className="mt-4" onClick={discover} disabled={busy==='discover'}>Analyze my Career Vault</Button></div>}</Card>
  <Card title="Active & draft personas"><div className="space-y-3">{personas.length?personas.map((p:any)=><div key={p.id} className="flex flex-col gap-3 rounded-xl border p-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><h3 className="font-semibold">{p.name}</h3><Badge tone={p.is_active?'good':'muted'}>{p.is_active?'Active':'Draft'}</Badge></div><p className="mt-1 text-sm text-muted-foreground">{p.positioning||p.description}</p><p className="mt-1 text-xs text-muted-foreground">Targets: {(p.target_titles||[]).join(', ')||'Not defined'}</p></div>{!p.is_active&&<button onClick={async()=>{setBusy(p.id);try{await apiClient.activatePersona(p.id);await load()}catch(e:any){setMsg(e.message)}finally{setBusy('')}}} className="rounded-xl border px-3 py-2 text-xs font-semibold hover:bg-muted">Activate</button>}</div>):<p className="text-sm text-muted-foreground">No personas have been activated. Suggested personas will appear above once sufficient evidence exists.</p>}</div></Card>
 </div><aside className="space-y-5"><Card title="How CareerOS keeps personas truthful"><div className="space-y-3 text-sm text-muted-foreground"><p><strong className="text-foreground">One source of truth.</strong> Personas do not fork your employment, education, certifications or skills.</p><p><strong className="text-foreground">Positioning, not invention.</strong> A persona changes emphasis and target titles; it cannot create a credential or employer.</p><p><strong className="text-foreground">Evidence-aware.</strong> Suggestions show why they were proposed and what evidence could strengthen them.</p><p><strong className="text-foreground">JD-ready.</strong> A future opportunity can select the best positioning lens without changing your canonical career history.</p></div></Card><Card title="Career Vault foundation"><p className="text-sm text-muted-foreground">{data?.experiences?.length||0} employment records · {data?.skills?.length||0} skills · {data?.certifications?.length||0} certifications · {data?.documents?.length||0} source documents</p><a href="/career-vault" className="mt-3 inline-block text-sm font-semibold text-primary">Open Career Vault →</a></Card></aside></div></CareerOSShell>
}
