'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { CareerOSShell, Card, Badge, Button } from '@/components/CareerOSShell';
import { apiClient, resolveApiBaseUrl } from '@/lib/api/client';
import { useTheme, type CareerOSTheme } from '@/contexts/ThemeContext';

type Connection={id:string;provider:string;provider_email?:string;scopes?:string[];last_used?:string;token_expires_at?:string};
const themeOptions:Array<{key:CareerOSTheme;title:string;description:string}>=[{key:'light',title:'Light',description:'Bright professional workspace'},{key:'dark',title:'Dark',description:'Premium low-light career workspace'},{key:'techno',title:'Command',description:'Translucent intelligence operating-system mode'}];
const menu=[['appearance','Appearance'],['account','Account & session'],['connections','Email & communication sources'],['privacy','Privacy & evidence'],['system','System health']];
export default function Settings(){
 const [me,setMe]=useState<any>();const [health,setHealth]=useState<any>();const [connections,setConnections]=useState<Connection[]>([]);const [diagnostics,setDiagnostics]=useState<any>(null);const [msg,setMsg]=useState('');const [section,setSection]=useState('appearance');const [busy,setBusy]=useState('');const [developer,setDeveloper]=useState(false);const {theme,setTheme}=useTheme();
 const loadConnections=async()=>{try{const d=await apiClient.connectionDiagnostics();setDiagnostics(d);setConnections(d.external_identities||[])}catch(e:any){setMsg(e.message||'Unable to load connection diagnostics')}};
 useEffect(()=>{Promise.all([apiClient.me(),apiClient.healthCheck()]).then(([u,h])=>{setMe(u);setHealth(h)}).catch(e=>setMsg(e.message));loadConnections();apiClient.get('/api/v1/developer/status').then(()=>setDeveloper(true)).catch(()=>setDeveloper(false));const params=new URLSearchParams(window.location.search);const oauth=params.get('oauth');if(oauth==='connected'){setSection('connections');setMsg(`${params.get('provider')||'Provider'} connection completed.`)}else if(oauth==='error'){setSection('connections');setMsg(params.get('message')||'OAuth connection failed.')}} ,[]);
 const connectGmail=async()=>{setBusy('gmail');setMsg('');try{const token=localStorage.getItem('access_token')||localStorage.getItem('careeros_token');const r=await fetch(`${resolveApiBaseUrl()}/api/v1/auth/oauth/google/gmail/authorize-url`,{method:'POST',headers:{Authorization:`Bearer ${token}`}});const body=await r.json();if(!r.ok)throw new Error(body.detail||'Unable to start Gmail authorization');window.location.href=body.authorization_url}catch(e:any){setMsg(e.message||'Unable to connect Gmail');setBusy('')}};
 return <CareerOSShell><header className="mb-6 border-b pb-6"><p className="text-xs font-semibold uppercase tracking-[.16em] text-primary">Application</p><h1 className="mt-1 text-3xl font-bold tracking-tight sm:text-4xl">Settings</h1><p className="mt-2 max-w-3xl text-sm text-muted-foreground">Appearance, account access, email sources, privacy and system behavior. Your career identity is managed in Profile Setup.</p></header><div className="grid gap-5 lg:grid-cols-[245px_minmax(0,1fr)]"><aside className="h-fit rounded-2xl border bg-card p-2 lg:sticky lg:top-28"><p className="px-3 py-2 text-[10px] font-bold uppercase tracking-[.16em] text-muted-foreground">Application settings</p>{menu.map(([key,label])=><button key={key} onClick={()=>setSection(key)} className={`w-full rounded-xl px-3 py-2.5 text-left text-sm font-medium transition ${section===key?'bg-primary/10 text-primary':'text-muted-foreground hover:bg-muted hover:text-foreground'}`}>{label}</button>)}{developer&&<Link href="/settings/developer" className="mt-2 block rounded-xl border border-primary/20 bg-primary/5 px-3 py-2.5 text-sm font-semibold text-primary">Developer Mode</Link>}<Link href="/project-tracker" className="mt-2 block rounded-xl px-3 py-2.5 text-sm font-medium text-muted-foreground hover:bg-muted">Project control</Link></aside><div className="space-y-4">
 {section==='appearance'&&<Card title="Application appearance" className="techno-glow"><div className="grid gap-3 md:grid-cols-3">{themeOptions.map(option=><button key={option.key} type="button" onClick={()=>setTheme(option.key)} className={`relative min-h-32 rounded-2xl border p-4 text-left transition ${theme===option.key?'border-primary bg-primary/10':'bg-background/40 hover:border-primary/40 hover:bg-muted/40'}`}>{theme===option.key&&<span className="absolute right-3 top-3 rounded-full bg-primary/15 px-2 py-1 text-[10px] font-bold text-primary">Active</span>}<span className="block text-base font-semibold">{option.title}</span><span className="mt-2 block text-xs leading-5 text-muted-foreground">{option.description}</span></button>)}</div></Card>}
 {section==='account'&&<Card title="Account & current session"><div className="grid gap-5 md:grid-cols-3"><div><p className="text-xs text-muted-foreground">Identity</p><p className="mt-1 font-medium">{me?.name||me?.email||'—'}</p></div><div><p className="text-xs text-muted-foreground">Email</p><p className="mt-1 break-words text-sm">{me?.email||'—'}</p></div><div><p className="text-xs text-muted-foreground">Authentication</p><div className="mt-1"><Badge tone="good">Authenticated</Badge></div></div></div></Card>}
 {section==='connections'&&<div className="space-y-4"><Card title="Email & communication sources"><p className="text-sm leading-6 text-muted-foreground">CareerOS keeps account authentication separate from the mailbox you use for career communication. Connect one or more supported mailboxes; future email intelligence can detect recruiter messages, job alerts and application updates without assuming everyone uses Gmail.</p><div className="mt-4 grid gap-3 md:grid-cols-2">{(diagnostics?.provider_catalog||[]).map((p:any)=><div key={p.provider} className="rounded-2xl border bg-background/25 p-4"><div className="flex items-center justify-between gap-3"><div><p className="font-semibold">{p.label}</p><p className="mt-1 text-xs text-muted-foreground">{p.capabilities?.join(' · ')}</p></div><Badge tone={p.status==='available'?'blue':'muted'}>{p.status==='available'?'Available':'Coming later'}</Badge></div>{p.provider==='google'&&<Button className="mt-3" onClick={connectGmail} disabled={busy==='gmail'}>{busy==='gmail'?'Connecting…':'Connect Gmail / Google Workspace'}</Button>}</div>)}</div></Card>
 <Card title="Connection diagnostics"><div className="space-y-3">{connections.map((c:any)=><div key={c.id} className="rounded-xl border p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-semibold capitalize">{c.provider}</p><p className="mt-1 text-xs text-muted-foreground">{c.provider_email||'Mailbox identity not returned'}</p></div><Badge tone="good">Connected</Badge></div><div className="mt-3 grid gap-2 text-xs sm:grid-cols-3"><div><span className="text-muted-foreground">Token</span><p className="font-semibold">{c.token_status||'present'}</p></div><div><span className="text-muted-foreground">Expiry</span><p className="font-semibold">{c.token_expires_at?new Date(c.token_expires_at).toLocaleString():'Not reported'}</p></div><div><span className="text-muted-foreground">Scopes</span><p className="font-semibold break-all">{(c.scopes||[]).join(', ')||'Not reported'}</p></div></div></div>)}{!connections.length&&<p className="text-sm text-muted-foreground">No external mailbox or identity connection is recorded yet.</p>}</div></Card><Card title="Google Gmail setup"><p className="text-sm text-muted-foreground">CareerOS requests readonly Gmail access for email intelligence. It does not request unrestricted <code>mail.google.com</code> access.</p><div className="mt-3 rounded-xl border bg-background/30 p-3 text-xs leading-5"><p><strong>Requested:</strong> openid · email · profile · gmail.readonly</p><p><strong>Purpose:</strong> detect career-related incoming mail and threads.</p><p><strong>Not requested:</strong> Gmail modify, send, or full mailbox access.</p></div></Card></div>}
 {section==='privacy'&&<Card title="Privacy & evidence"><div className="space-y-3 text-sm leading-6 text-muted-foreground"><p>Original career documents remain evidence. OCR, classification and profile fields are derived information.</p><p>CareerOS keeps document provenance internally while presenting human-readable evidence relationships.</p><p>OAuth scopes are explicit and limited to the connected feature. Sensitive communication remains human-approved.</p></div></Card>}
 {section==='system'&&<div className="grid gap-4 md:grid-cols-2"><Card title="API health"><p className="text-sm text-muted-foreground">Backend: <strong className="text-primary">{health?.status||'checking…'}</strong></p></Card><Card title="Connection architecture"><p className="text-sm leading-6 text-muted-foreground">Email connectors use a common capability model so Gmail, Microsoft 365 and later IMAP/Yahoo/iCloud connectors can feed the same Opportunity intelligence pipeline.</p></Card></div>}
 </div></div>{msg&&<div className="mt-4 rounded-xl border bg-card px-4 py-3 text-sm">{msg}</div>}</CareerOSShell>;
}
