'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { CareerOSShell, Card, PageHeader, Button, Badge } from '@/components/CareerOSShell';
import { apiClient } from '@/lib/api/client';

function OpenEvidence({id,label}:{id:string;label:string}){const open=async()=>{try{const blob=await apiClient.openDocumentContent(id);const url=URL.createObjectURL(blob);window.open(url,'_blank','noopener,noreferrer');setTimeout(()=>URL.revokeObjectURL(url),60000)}catch(e:any){alert(e.message)}};return <button onClick={open} className="rounded-lg border px-2.5 py-1.5 text-xs font-semibold text-primary hover:bg-primary/5">{label}</button>}

export default function CareerVault(){
 const [data,setData]=useState<any>();const [msg,setMsg]=useState('');
 useEffect(()=>{apiClient.identityOverview().then(setData).catch(e=>setMsg(e.message||'Unable to load Career Vault'))},[]);
 if(!data)return <CareerOSShell><div className="grid min-h-[60vh] place-items-center text-sm text-muted-foreground">Loading Career Vault…</div></CareerOSShell>;
 const p=data.profile||{};
 return <CareerOSShell><PageHeader eyebrow="Professional Identity" title="Career Vault" description="The structured source of truth behind your Career Passport. It stores career facts, supporting evidence and review states—not a second profile form." action={<Link href="/profile/setup"><Button>Correct / add a fact</Button></Link>}/>
 {msg&&<div className="mb-4 rounded-xl border bg-card px-4 py-3 text-sm">{msg}</div>}
 <div className="grid gap-5 lg:grid-cols-3"><Card><p className="text-xs text-muted-foreground">Canonical employment</p><p className="mt-1 text-3xl font-bold">{data.experiences?.length||0}</p><p className="mt-2 text-xs text-muted-foreground">Derived from employment/experience evidence.</p></Card><Card><p className="text-xs text-muted-foreground">Education records</p><p className="mt-1 text-3xl font-bold">{data.educations?.length||0}</p><p className="mt-2 text-xs text-muted-foreground">Degree, transcript and education evidence can converge here.</p></Card><Card><p className="text-xs text-muted-foreground">Credentials</p><p className="mt-1 text-3xl font-bold">{data.certifications?.length||0}</p><p className="mt-2 text-xs text-muted-foreground">Skills never become certifications just because they appear nearby.</p></Card></div>
 <div className="mt-5 space-y-5"><Card title="Employment facts"><div className="space-y-3">{data.experiences?.map((x:any)=><div key={x.id} className="rounded-xl border p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{x.title} · {x.company}</p><p className="mt-1 text-xs text-muted-foreground">{String(x.start_date||'').slice(0,10)||'Date not recorded'} — {x.is_current?'Present':String(x.end_date||'').slice(0,10)||'Date not recorded'}</p></div><Badge tone="blue">{x.evidence?.length?'Evidence linked':'Evidence pending'}</Badge></div><div className="mt-3 flex flex-wrap gap-2">{x.evidence?.map((e:any)=><OpenEvidence key={e.document_id} id={e.document_id} label={e.filename||'Evidence'}/>)}</div></div>)}{!data.experiences?.length&&<p className="text-sm text-muted-foreground">No canonical employment facts yet.</p>}</div></Card>
 <div className="grid gap-5 lg:grid-cols-2"><Card title="Education facts"><div className="space-y-3">{data.educations?.map((x:any)=><div key={x.id} className="rounded-xl border p-4"><p className="font-semibold">{x.degree}</p><p className="mt-1 text-sm text-muted-foreground">{x.institution}{x.field_of_study?` · ${x.field_of_study}`:''}</p><div className="mt-2 flex flex-wrap gap-2">{x.evidence?.length?x.evidence.map((e:any)=><OpenEvidence key={e.document_id} id={e.document_id} label={e.filename||'Evidence'}/>):<Badge>Evidence pending</Badge>}</div></div>)}</div></Card><Card title="Certification facts"><div className="space-y-3">{data.certifications?.map((x:any)=><div key={x.id} className="rounded-xl border p-4"><p className="font-semibold">{x.name}</p><p className="mt-1 text-sm text-muted-foreground">{x.issuer||'Issuer not recorded'}{x.credential_reference?` · ${x.credential_reference}`:''}</p><div className="mt-2 flex flex-wrap gap-2">{x.evidence?.length?x.evidence.map((e:any)=><OpenEvidence key={e.document_id} id={e.document_id} label={e.filename||'Evidence'}/>):<Badge>CV reported</Badge>}</div></div>)}</div></Card></div>
 <Card title="Career preferences"><div className="grid gap-3 md:grid-cols-3"><div className="rounded-xl border p-4"><p className="text-xs text-muted-foreground">Target roles</p><p className="mt-1 text-sm font-semibold">{p.work_preferences?.target_roles?.join(', ')||'Open / not specified'}</p></div><div className="rounded-xl border p-4"><p className="text-xs text-muted-foreground">Preferred work locations</p><p className="mt-1 text-sm font-semibold">{p.work_preferences?.preferred_locations?.join(', ')||'Open / not specified'}</p></div><div className="rounded-xl border p-4"><p className="text-xs text-muted-foreground">Work arrangement</p><p className="mt-1 text-sm font-semibold">{p.work_preferences?.work_arrangement||'Flexible / not specified'}</p></div></div><p className="mt-3 text-xs text-muted-foreground">These are user preferences. They are intentionally kept separate from evidence-backed career facts.</p></Card>
 </div></CareerOSShell>;
}
