'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useAuth } from '@/contexts/AuthContext';
import DocumentUpload from '@/components/documents/DocumentUpload';
import { apiClient } from '@/lib/api/client';
import { CareerOSShell, Card, PageHeader, Badge, Button } from '@/components/CareerOSShell';

type DocumentRecord={id:string;filename?:string;file_size?:unknown;document_category?:unknown;document_subcategory?:unknown;status?:unknown;extraction_status?:unknown;classification_confidence?:unknown;created_at?:string;detected_type?:string;verification_status?:string;user_label?:string;processing_status?:any};
type JobState={jobId:string;documentId:string;status:string;stage:string;failedStage?:string;message:string;progress:number;error?:string;result?:any;startedAt:number};
const text=(value:unknown,fallback='—')=>{if(value===null||value===undefined||value==='')return fallback;if(typeof value==='string'||typeof value==='number')return String(value);try{return JSON.stringify(value)}catch{return fallback}};
const stages=[['queued','Queued'],['validating_document','Validate CV'],['routing','Select AI route'],['ai_processing','AI extraction'],['reconciling_profile','Reconcile facts'],['profile_validation','Validate profile'],['persisting','Persist profile'],['completed','Completed']];
const fmtTime=(value?:string)=>value?new Date(value).toLocaleTimeString():'—';
const fmtMs=(value?:number|null)=>value==null?'—':`${Number(value).toFixed(1)} ms`;
const duration=(seconds:number)=>{const s=Math.max(0,Math.floor(seconds));const h=Math.floor(s/3600);const m=Math.floor((s%3600)/60);const sec=s%60;return h?`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}`:`${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}`};
const eventLabel=(type?:string)=>({GENERATION_DELTA:'Model is generating structured output',GENERATION_STARTED:'Model generation started',GENERATION_COMPLETED:'Model generation completed',GENERATION_FAILED:'Model generation failed',PROVIDER_STREAM_STARTED:'Provider stream connected',PROVIDER_SELECTED:'AI provider selected',TASK_IDENTIFIED:'Task identified',HEALTH_GATE:'Provider health gate checked',ROUTING_FAILED:'Routing failed'} as Record<string,string>)[type||'']||type||'Runtime activity';

export default function DocumentsPage(){
 const {token,isAuthenticated,isLoading}=useAuth();const router=useRouter();
 const [documents,setDocuments]=useState<DocumentRecord[]>([]);const [loading,setLoading]=useState(true);const [activeJob,setActiveJob]=useState<JobState|null>(null);const [runtimeTrace,setRuntimeTrace]=useState<any>(null);const [showJobPanel,setShowJobPanel]=useState(false);const [message,setMessage]=useState('');const [clock,setClock]=useState(Date.now());
 useEffect(()=>{if(!isLoading&&!isAuthenticated)router.replace('/login')},[isLoading,isAuthenticated,router]);
 const load=async()=>{setLoading(true);try{const data=await apiClient.get<DocumentRecord[]>('/api/v1/documents/');setDocuments(Array.isArray(data)?data.filter(d=>text(d.document_category,'')==='cv'):[])}finally{setLoading(false)}};
 const reconcile=async(documentId:string)=>{setMessage('');setRuntimeTrace(null);const startedAt=Date.now();try{const result=await apiClient.startAIReconciliationJob(documentId);const jobId=result.job_id;if(!jobId)throw new Error('CareerOS did not return a reconciliation job ID');setActiveJob({jobId,documentId,status:'accepted',stage:'queued',message:'CV reconciliation queued',progress:0,startedAt});setShowJobPanel(true);await load()}catch(e:any){setMessage(e.message||'Unable to start CV reconciliation')}};
 useEffect(()=>{if(!activeJob||activeJob.status==='completed'||activeJob.status==='failed')return;let cancelled=false;const poll=async()=>{try{const result=await apiClient.aiReconciliationJob(activeJob.documentId,activeJob.jobId);if(cancelled)return;setActiveJob(j=>j?{...j,status:result.status,stage:result.stage||j.stage,failedStage:result.failed_stage||j.failedStage,message:result.message||j.message,progress:Number(result.progress||0),error:result.error,result:result.result,startedAt:j.startedAt}:j);if(result.status==='completed'||result.status==='failed'){await load()}}catch(e:any){if(!cancelled)setActiveJob(j=>j?{...j,status:'failed',stage:'failed',failedStage:j.stage,message:'Unable to read reconciliation status',progress:j.progress,error:e.message,startedAt:j.startedAt}:j)}};void poll();const timer=window.setInterval(()=>void poll(),1000);return()=>{cancelled=true;window.clearInterval(timer)}},[activeJob?.jobId,activeJob?.documentId,activeJob?.status]);
 useEffect(()=>{if(!activeJob)return;let cancelled=false;const pollTrace=async()=>{try{const result=await apiClient.intelligenceRuntimeTraces(50);const candidates=(result.traces||[]).filter((trace:any)=>trace.task_type!=='provider_health_check'&&(trace.context?.document_id===activeJob.documentId||trace.context?.filename===(documents.find(d=>d.id===activeJob.documentId)?.filename)));const match=candidates.sort((a:any,b:any)=>new Date(b.updated_at||b.started_at||0).getTime()-new Date(a.updated_at||a.started_at||0).getTime())[0]||null;if(!cancelled)setRuntimeTrace(match)}catch{if(!cancelled)setRuntimeTrace(null)}};void pollTrace();const timer=window.setInterval(()=>void pollTrace(),1000);return()=>{cancelled=true;window.clearInterval(timer)}},[activeJob?.documentId,documents]);
 useEffect(()=>{if(!activeJob)return;const timer=window.setInterval(()=>setClock(Date.now()),1000);return()=>window.clearInterval(timer)},[activeJob?.jobId,activeJob?.status]);
 useEffect(()=>{if(activeJob?.status==='completed')setMessage('CV reconciliation completed. Refreshing the Professional Profile data.');if(activeJob?.status==='failed')setMessage(activeJob.error||`CV reconciliation failed during ${activeJob.failedStage||'an unknown stage'}.`)},[activeJob?.status,activeJob?.error,activeJob?.failedStage]);
 useEffect(()=>{if(isAuthenticated&&token)void load()},[isAuthenticated,token]);
 if(isLoading||loading)return <div className="grid min-h-screen place-items-center bg-background">Loading CV workspace…</div>;if(!isAuthenticated)return null;
 const activeDoc=documents.find(d=>d.id===activeJob?.documentId);
 const generationEvent=runtimeTrace?.events?.find((event:any)=>event.type==='GENERATION_STARTED');
 const runtimeStartedAt=runtimeTrace?.started_at?new Date(runtimeTrace.started_at).getTime():null;
 const jobElapsed=activeJob?Math.max(0,(clock-activeJob.startedAt)/1000):0;
 const runtimeElapsed=runtimeStartedAt?Math.max(0,(clock-runtimeStartedAt)/1000):0;
 const timeoutSeconds=Number(generationEvent?.timeout_seconds||0);
 const remainingSeconds=timeoutSeconds?Math.max(0,timeoutSeconds-runtimeElapsed):null;
 const native=runtimeTrace?.provider_metrics||{};
 const events=runtimeTrace?.events||[];
 const latestEvent=events.length?events[events.length-1]:null;
 const lastActivityAt=latestEvent?.timestamp||runtimeTrace?.updated_at||null;
 const activityAge=lastActivityAt?Math.max(0,(clock-new Date(lastActivityAt).getTime())/1000):null;
 const outputChars=Number(runtimeTrace?.output_chars||0);
 const outputRate=runtimeElapsed>0?outputChars/runtimeElapsed:0;
 const currentOperation=activeJob?.status==='failed'?`Failed during ${activeJob.failedStage||activeJob.stage}`:latestEvent?.type?eventLabel(latestEvent.type):activeJob?.message||'Waiting for runtime trace';
 const streamActive=latestEvent?.type==='GENERATION_DELTA'&&activityAge!=null&&activityAge<5;
 const runtimeStatus=runtimeTrace?.status||'waiting';
 const traceVisible=!!runtimeTrace;
 const statusTone=activeJob?.status==='failed'?'warn':activeJob?.status==='completed'?'good':streamActive?'good':'blue';
 const progress=Math.min(100,Math.max(0,Number(activeJob?.progress||0)));
 const timerLabel=activeJob?.status==='completed'?'Completed':activeJob?.status==='failed'?'Stopped':duration(jobElapsed);
 return <CareerOSShell>
  <PageHeader eyebrow="Professional Identity" title="CV & Documents" description="Upload CV versions here. Reconcile an uploaded CV with AI to build the Professional Profile." action={<Link href="/evidence-library" className="rounded-xl border bg-card px-4 py-2.5 text-sm font-semibold hover:bg-muted">Add Evidence</Link>}/>
  {message&&<div className="mb-5 rounded-xl border bg-card px-4 py-3 text-sm">{message}</div>}
  {activeJob&&activeJob.status==='running'&&<button type="button" onClick={()=>setShowJobPanel(true)} className="mb-5 w-full rounded-xl border bg-primary/5 px-4 py-3 text-left text-sm"><div className="flex flex-wrap items-center justify-between gap-2"><div><strong>AI processing in background</strong><span className="ml-2 text-muted-foreground">{activeJob.message} · {progress}%</span>{runtimeTrace?.selected_provider&&<span className="ml-2 text-muted-foreground">· {runtimeTrace.selected_provider} · {runtimeTrace.selected_model}</span>}</div><span className="font-mono text-sm font-bold tabular-nums">{timerLabel}</span></div></button>}
  <section id="cv" className="scroll-mt-36"><Card title="Upload CV" className="techno-glow"><div className="grid gap-5 lg:grid-cols-[minmax(0,1.3fr)_minmax(260px,.7fr)]"><DocumentUpload category="cv" onUploadComplete={()=>void load()}/><div className="rounded-xl border bg-background/30 p-5"><p className="text-xs font-semibold uppercase tracking-[.14em] text-primary">CV-first identity building</p><h3 className="mt-2 text-lg font-semibold">One Professional Profile</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Upload multiple CV versions when useful. Reconciliation combines explicit CV facts into one CareerOS Professional Profile. Professional certificates and letters belong in the Evidence Library.</p><div className="mt-4 space-y-2 text-sm"><div className="flex justify-between"><span className="text-muted-foreground">CV versions</span><strong>{documents.length}</strong></div><div className="flex justify-between"><span className="text-muted-foreground">Processed</span><strong>{documents.filter(d=>text(d.extraction_status,'')==='complete').length}</strong></div></div></div></div></Card></section>
  <div className="mt-5"><Card title="CV versions"><div className="divide-y">{documents.length?documents.slice(0,20).map(doc=><div key={doc.id} className="flex flex-col gap-3 py-4 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{doc.user_label||doc.filename||'CV version'}</p><div className="mt-1 flex flex-wrap gap-2 text-xs"><Badge tone="blue">CV / Resume</Badge><Badge tone={text(doc.status,'')==='failed'?'warn':'muted'}>{text(doc.status,'unknown')}</Badge><Badge tone={text(doc.extraction_status,'')==='complete'?'good':text(doc.extraction_status,'')==='failed'?'warn':'blue'}>{text(doc.extraction_status,'unknown')}</Badge>{typeof doc.classification_confidence==='number'&&<span>{Math.round(Number(doc.classification_confidence)*100)}% classified</span>}</div>{text(doc.extraction_status,'')==='failed'&&<p className="mt-1 text-xs text-amber-700 dark:text-amber-300">Deterministic extraction failed; the CV source text remains available for AI reconciliation.</p>}</div><div className="shrink-0"><Button onClick={()=>void reconcile(doc.id)} disabled={!!activeJob&&activeJob.status==='running'}>{activeJob?.documentId===doc.id&&activeJob.status==='running'?'AI processing…':'Reconcile with AI'}</Button></div></div>):<div className="rounded-xl border border-dashed p-10 text-center"><p className="font-semibold">No CV uploaded</p><p className="mt-1 text-sm text-muted-foreground">Upload your CV to create the first Professional Profile draft.</p></div>}</div></Card></div>
  {showJobPanel&&activeJob&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4 backdrop-blur-[2px]"><div className="flex max-h-[92vh] w-full max-w-6xl flex-col overflow-hidden rounded-2xl border bg-background shadow-2xl">
   <div className="border-b p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div className="min-w-0"><p className="text-xs font-semibold uppercase tracking-[.14em] text-primary">CareerOS Global Intelligence · Live execution</p><h2 className="mt-1 text-xl font-semibold">CV Reconciliation</h2><p className="mt-1 truncate text-sm text-muted-foreground">{activeDoc?.user_label||activeDoc?.filename||'CV'} · job {activeJob.jobId.slice(0,8)}</p></div><div className="flex items-center gap-2"><div className="rounded-xl border bg-background/60 px-4 py-2 text-right"><p className="text-[10px] uppercase tracking-[.12em] text-muted-foreground">Job timer</p><p className="font-mono text-2xl font-bold tabular-nums">{timerLabel}</p></div><button type="button" onClick={()=>setShowJobPanel(false)} className="rounded-lg border px-3 py-2 text-sm">{activeJob.status==='running'?'Run in background':'Close'}</button></div></div>
   <div className="mt-4 grid gap-3 md:grid-cols-4"><div className="rounded-xl border bg-background/30 p-3"><p className="text-[10px] uppercase tracking-[.12em] text-muted-foreground">Current stage</p><p className="mt-1 text-sm font-semibold">{activeJob.stage.replaceAll('_',' ')}</p><p className="mt-1 text-xs text-muted-foreground">{progress}% complete</p></div><div className="rounded-xl border bg-background/30 p-3"><p className="text-[10px] uppercase tracking-[.12em] text-muted-foreground">Current operation</p><p className="mt-1 text-sm font-semibold">{currentOperation}</p><p className="mt-1 text-xs text-muted-foreground">{streamActive?'Receiving provider stream':'Based on latest runtime event'}</p></div><div className="rounded-xl border bg-background/30 p-3"><p className="text-[10px] uppercase tracking-[.12em] text-muted-foreground">AI runtime</p><p className="mt-1 text-sm font-semibold">{traceVisible?`${runtimeTrace.selected_provider||'provider pending'}${runtimeTrace.selected_model?` · ${runtimeTrace.selected_model}`:''}`:'Trace not visible yet'}</p><p className="mt-1 text-xs text-muted-foreground">Generation {runtimeElapsed?duration(runtimeElapsed):'—'}</p></div><div className="rounded-xl border bg-background/30 p-3"><p className="text-[10px] uppercase tracking-[.12em] text-muted-foreground">Last activity</p><p className="mt-1 text-sm font-semibold">{activityAge==null?'—':activityAge<2?'Just now':`${Math.floor(activityAge)}s ago`}</p><p className="mt-1 text-xs text-muted-foreground">{events.length} runtime events</p></div></div>
   <div className="mt-4 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full bg-primary transition-all duration-500" style={{width:`${progress}%`}}/></div>
   </div>
   <div className="grid min-h-0 flex-1 gap-5 overflow-y-auto p-5 lg:grid-cols-[.8fr_1.2fr]">
    <div className="space-y-4"><div className="rounded-xl border p-4"><div className="flex items-center justify-between"><p className="text-xs font-semibold uppercase tracking-[.12em]">Pipeline</p><Badge tone={statusTone}>{activeJob.status}</Badge></div><div className="mt-4 space-y-3">{stages.map(([key,label])=>{const failedIndex=stages.findIndex(x=>x[0]===activeJob.failedStage);const currentIndex=stages.findIndex(x=>x[0]===activeJob.stage);const index=stages.findIndex(x=>x[0]===key);const referenceIndex=activeJob.status==='failed'?failedIndex:currentIndex;const done=activeJob.status==='completed'||(referenceIndex>=0&&index<referenceIndex);const current=activeJob.status==='running'&&key===activeJob.stage;const failed=activeJob.status==='failed'&&key===activeJob.failedStage;return <div key={key} className="flex items-start gap-3"><div className={`mt-0.5 grid h-7 w-7 shrink-0 place-items-center rounded-full border text-xs ${done?'bg-primary text-primary-foreground':failed?'border-destructive bg-destructive/10 text-destructive':current?'border-primary bg-primary/10 text-primary':'bg-muted'}`}>{done?'✓':failed?'!':current?'●':''}</div><div className="min-w-0 flex-1"><div className={`text-sm font-medium ${failed?'text-destructive':''}`}>{label}</div>{current&&<p className="mt-0.5 text-xs text-muted-foreground">{activeJob.message}</p>}{failed&&<p className="mt-0.5 text-xs text-destructive">{activeJob.error||'Failed at this stage.'}</p>}</div>{current&&<span className="text-xs font-semibold tabular-nums text-muted-foreground">{progress}%</span>}</div>})}</div></div>
     <div className="rounded-xl border p-4"><div className="flex items-center justify-between"><p className="text-xs font-semibold uppercase tracking-[.12em]">Execution telemetry</p><Badge tone={runtimeStatus==='completed'?'good':runtimeStatus==='failed'?'warn':streamActive?'good':'blue'}>{runtimeStatus}</Badge></div>{traceVisible?<><div className="mt-3 grid gap-2 sm:grid-cols-2"><div className="rounded-lg border p-3"><p className="text-[10px] text-muted-foreground">Provider</p><p className="mt-1 text-xs font-semibold">{runtimeTrace.selected_provider||'Selecting…'}</p></div><div className="rounded-lg border p-3"><p className="text-[10px] text-muted-foreground">Model</p><p className="mt-1 text-xs font-semibold">{runtimeTrace.selected_model||'Selecting…'}</p></div><div className="rounded-lg border p-3"><p className="text-[10px] text-muted-foreground">Job elapsed</p><p className="mt-1 font-mono text-xs font-semibold tabular-nums">{duration(jobElapsed)}</p></div><div className="rounded-lg border p-3"><p className="text-[10px] text-muted-foreground">Generation elapsed</p><p className="mt-1 font-mono text-xs font-semibold tabular-nums">{duration(runtimeElapsed)}</p></div><div className="rounded-lg border p-3"><p className="text-[10px] text-muted-foreground">Output</p><p className="mt-1 text-xs font-semibold">{outputChars.toLocaleString()} chars · {outputRate.toFixed(1)} chars/s</p></div><div className="rounded-lg border p-3"><p className="text-[10px] text-muted-foreground">Fallback</p><p className="mt-1 text-xs font-semibold">{runtimeTrace.fallback_used?'YES':'NO'}</p></div></div>{timeoutSeconds>0&&<div className={`mt-3 rounded-lg border p-3 ${remainingSeconds!=null&&remainingSeconds<30?'border-amber-500/40 bg-amber-500/5':''}`}><div className="flex items-center justify-between"><span className="text-xs font-semibold">Configured generation timeout</span><span className="font-mono text-xs font-semibold tabular-nums">{remainingSeconds}s remaining</span></div><p className="mt-1 text-[11px] text-muted-foreground">This is the actual configured timeout, not a simulated progress countdown.</p></div>}
     {runtimeTrace.thinking_available&&<div className="mt-3 rounded-lg border border-primary/20 bg-primary/5 p-3"><div className="flex items-center justify-between"><p className="text-[10px] font-semibold uppercase tracking-[.12em] text-primary">Provider-native thinking</p><span className="text-[10px] text-muted-foreground">{runtimeTrace.thinking_chars||0} chars</span></div><pre className="mt-2 max-h-40 overflow-auto whitespace-pre-wrap font-mono text-[10px] leading-4">{runtimeTrace.thinking_text||'Thinking stream active; waiting for content…'}</pre></div>}
     {runtimeTrace.output_preview&&<div className="mt-3 rounded-lg border p-3"><div className="flex items-center justify-between"><p className="text-[10px] font-semibold uppercase tracking-[.12em]">Live generation output</p><span className="text-[10px] text-muted-foreground">{outputChars.toLocaleString()} chars</span></div><pre className="mt-2 max-h-40 overflow-auto whitespace-pre-wrap font-mono text-[10px] leading-4">{runtimeTrace.output_preview}</pre></div>}
     {Object.keys(native).length>0&&<div className="mt-3 grid gap-2 sm:grid-cols-2"><div className="rounded-lg border p-3"><p className="text-[10px] text-muted-foreground">Total duration</p><p className="mt-1 text-xs font-semibold">{nativeMs(native.total_duration)}</p></div><div className="rounded-lg border p-3"><p className="text-[10px] text-muted-foreground">Model load</p><p className="mt-1 text-xs font-semibold">{nativeMs(native.load_duration)}</p></div><div className="rounded-lg border p-3"><p className="text-[10px] text-muted-foreground">Prompt evaluation</p><p className="mt-1 text-xs font-semibold">{nativeMs(native.prompt_eval_duration)} · {native.prompt_eval_count??'—'} tokens</p></div><div className="rounded-lg border p-3"><p className="text-[10px] text-muted-foreground">Generation evaluation</p><p className="mt-1 text-xs font-semibold">{nativeMs(native.eval_duration)} · {native.eval_count??'—'} tokens</p></div><div className="rounded-lg border p-3 sm:col-span-2"><p className="text-[10px] text-muted-foreground">Stop reason</p><p className="mt-1 text-xs font-semibold">{native.done_reason||'—'}</p></div></div>}
     <div className="mt-3 rounded-lg border"><div className="flex items-center justify-between border-b px-3 py-2"><p className="text-[10px] font-semibold uppercase tracking-[.12em]">Live event stream</p><span className="text-[10px] text-muted-foreground">Newest event at bottom</span></div><div className="max-h-72 overflow-auto p-2 font-mono text-[10px]">{events.length?events.map((event:any,index:number)=><div key={`${event.timestamp}-${index}`} className="border-b py-1.5 last:border-0"><span className="text-muted-foreground">{fmtTime(event.timestamp)}</span> · <strong>{event.type}</strong> · {event.message}{event.provider?` · ${event.provider}`:''}{event.model?` · ${event.model}`:''}{event.reason?` · ${event.reason}`:''}{event.chars!=null?` · ${event.chars} chars`:''}{event.latency_ms!=null?` · ${fmtMs(event.latency_ms)}`:''}</div>):<div className="p-3 text-muted-foreground">No runtime events have been published yet.</div>}</div></div></>:<div className="mt-3 rounded-xl border border-dashed p-6"><p className="text-sm font-semibold">Runtime trace not visible yet</p><p className="mt-1 text-xs leading-5 text-muted-foreground">The reconciliation job is still tracked independently. CareerOS will attach the actual provider trace as soon as it is published; no fake provider activity is shown.</p><div className="mt-4 grid gap-2 sm:grid-cols-3"><div className="rounded-lg border p-3"><p className="text-[10px] text-muted-foreground">Job timer</p><p className="mt-1 font-mono text-lg font-bold tabular-nums">{duration(jobElapsed)}</p></div><div className="rounded-lg border p-3"><p className="text-[10px] text-muted-foreground">Stage</p><p className="mt-1 text-xs font-semibold">{activeJob.stage.replaceAll('_',' ')}</p></div><div className="rounded-lg border p-3"><p className="text-[10px] text-muted-foreground">Progress</p><p className="mt-1 text-xs font-semibold">{progress}%</p></div></div></div>}</div>
    </div>
   </div>
   {activeJob.status==='failed'&&<div className="border-t border-destructive/20 bg-destructive/5 px-5 py-4 text-sm text-destructive"><strong>Failure detected:</strong> {activeJob.error||`Reconciliation failed during ${activeJob.failedStage||'an unknown stage'}.`}</div>}
   {activeJob.status==='completed'&&<div className="border-t bg-muted/20 px-5 py-4 text-sm">Completed. The Professional Profile can now be refreshed to inspect the reconciled sections.</div>}
  </div></div>}
 </CareerOSShell>;
}
