'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useAuth } from '@/contexts/AuthContext';
import DocumentUpload from '@/components/documents/DocumentUpload';
import DocumentBulkUpload from '@/components/documents/DocumentBulkUpload';
import { apiClient } from '@/lib/api/client';
import { CareerOSShell, Card, PageHeader, Badge } from '@/components/CareerOSShell';

type DocumentRecord={id:string;original_filename?:unknown;filename?:unknown;file_size?:unknown;document_category?:unknown;document_subcategory?:unknown;status?:unknown;extraction_status?:unknown;classification_confidence?:unknown;created_at?:string;detected_type?:string;verification_status?:string};
const text=(value:unknown,fallback='—')=>{if(value===null||value===undefined||value==='')return fallback;if(typeof value==='string'||typeof value==='number')return String(value);try{return JSON.stringify(value)}catch{return fallback}};

export default function DocumentsPage(){
 const {token,isAuthenticated,isLoading}=useAuth();const router=useRouter();const [documents,setDocuments]=useState<DocumentRecord[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [category,setCategory]=useState('all');
 useEffect(()=>{if(!isLoading&&!isAuthenticated)router.replace('/login')},[isLoading,isAuthenticated,router]);
 const load=async()=>{setLoading(true);try{const data=await apiClient.get<DocumentRecord[]>('/api/v1/documents/');setDocuments(Array.isArray(data)?data:[]);setError('')}catch(e:any){setError(e?.message||'Unable to load documents')}finally{setLoading(false)}};
 useEffect(()=>{if(isAuthenticated&&token)void load()},[isAuthenticated,token]);
 const filtered=category==='all'?documents:documents.filter(d=>text(d.document_category,'')===category);const cvs=documents.filter(d=>text(d.document_category,'')==='cv');const processed=documents.filter(d=>text(d.extraction_status,'')==='complete').length;
 if(isLoading||loading)return <div className="grid min-h-screen place-items-center bg-background">Loading CV & Documents…</div>;if(!isAuthenticated)return null;
 return <CareerOSShell><PageHeader eyebrow="Professional Identity" title="CV & Documents" description="Upload one or more CVs and supporting career documents. CareerOS analyzes content, builds evidence-backed profile facts and keeps every source available in the Evidence Library." action={<Link href="/evidence-library" className="rounded-xl border bg-card px-4 py-2.5 text-sm font-semibold hover:bg-muted">Open Evidence Library</Link>}/>
 {error&&<div className="mb-4 rounded-xl border border-red-500/30 bg-red-500/10 px-4 py-3 text-sm text-red-500">{error}</div>}
 <section id="cv" className="scroll-mt-36"><Card title="Add your CVs" className="techno-glow"><div className="grid gap-5 lg:grid-cols-[minmax(0,1.3fr)_minmax(260px,.7fr)]"><DocumentUpload category="cv" onUploadComplete={()=>void load()}/><div className="rounded-xl border bg-background/30 p-5"><p className="text-xs font-semibold uppercase tracking-[.14em] text-primary">CV-first identity building</p><h3 className="mt-2 text-lg font-semibold">Upload multiple versions</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Keep a master CV plus role, region or specialty variants. They all contribute evidence to one Career Vault; CareerOS does not create separate profiles.</p><div className="mt-4 space-y-2 text-sm"><div className="flex justify-between"><span className="text-muted-foreground">CV versions</span><strong>{cvs.length}</strong></div><div className="flex justify-between"><span className="text-muted-foreground">Processed documents</span><strong>{processed}</strong></div></div></div></div></Card></section>
 <section id="vault" className="mt-5 scroll-mt-36"><Card title="Add supporting professional evidence"><p className="mb-4 text-sm text-muted-foreground">Certificates, degrees, transcripts, experience letters, awards, project evidence and other career records can strengthen the facts already found in your CV.</p><DocumentBulkUpload onComplete={()=>void load()}/></Card></section>
 <div className="mt-5 grid gap-4 md:grid-cols-3"><Card><p className="text-xs text-muted-foreground">Total documents</p><p className="mt-1 text-3xl font-bold">{documents.length}</p></Card><Card><p className="text-xs text-muted-foreground">CV / Resume versions</p><p className="mt-1 text-3xl font-bold">{cvs.length}</p></Card><Card><p className="text-xs text-muted-foreground">Evidence workspace</p><Link href="/evidence-library" className="mt-2 inline-block text-sm font-semibold text-primary">View detected types, links & confidence →</Link></Card></div>
 <div className="mt-5"><Card title="Recent uploads"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-muted-foreground">Classification is content-first. The original filename is retained for traceability.</p><select value={category} onChange={e=>setCategory(e.target.value)} className="careeros-input w-auto"><option value="all">All documents</option><option value="cv">CV / Resume</option><option value="employment">Employment</option><option value="certification">Certifications</option><option value="education">Education</option><option value="project">Projects</option><option value="achievement">Achievements</option><option value="other">Other</option></select></div>{filtered.length===0?<div className="rounded-xl border border-dashed p-10 text-center"><p className="font-semibold">No documents in this view</p><p className="mt-1 text-sm text-muted-foreground">Upload your CV or professional evidence above.</p></div>:<div className="divide-y">{filtered.slice(0,20).map(doc=>{const name=text(doc.filename||doc.original_filename,'document');const status=text(doc.status,'unknown');const extraction=text(doc.extraction_status,'unknown');const confidence=typeof doc.classification_confidence==='number'?Math.round(doc.classification_confidence*100):null;return <div key={doc.id} className="flex flex-col gap-3 py-4 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><Link href="/evidence-library" className="truncate text-sm font-semibold text-primary">{name}</Link><div className="mt-1 flex flex-wrap gap-2 text-xs text-muted-foreground"><Badge tone="blue">{text(doc.detected_type||`${doc.document_category||'other'}:${doc.document_subcategory||'unknown'}`)}</Badge><Badge tone={status==='failed'?'warn':'muted'}>{status}</Badge><Badge tone={extraction==='complete'?'good':'blue'}>{extraction}</Badge>{confidence!=null&&<span>{confidence}% confidence</span>}</div></div><Link href="/evidence-library" className="rounded-lg border px-3 py-2 text-xs font-semibold hover:bg-muted">Open Library</Link></div>})}</div>}</Card></div>
 </CareerOSShell>;
}
