"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useAuth } from "@/contexts/AuthContext";
import { apiClient, resolveApiBaseUrl } from "@/lib/api/client";
import { CareerOSShell, Card, PageHeader, Badge } from "@/components/CareerOSShell";

type Intelligence={profile:any;completeness:any;experience:any[];skills:any[];certifications:any[];education:any[];documents:any[];connections:any[];provenance:any[];readiness:any};

export default function ProfileIntelligencePage(){
  const {isAuthenticated,isLoading}=useAuth(); const router=useRouter(); const [data,setData]=useState<Intelligence|null>(null); const [loading,setLoading]=useState(true); const [message,setMessage]=useState("");
  const load=async()=>{try{setData(await apiClient.get<Intelligence>("/api/v1/profile/intelligence"));setMessage("")}catch(e:any){setMessage(e.message||"Failed to load profile intelligence")}finally{setLoading(false)}};
  useEffect(()=>{if(!isLoading&&!isAuthenticated)router.push('/login')},[isLoading,isAuthenticated,router]); useEffect(()=>{if(isAuthenticated)load()},[isAuthenticated]);
  const connectGmail=async()=>{try{const token=localStorage.getItem("access_token")||localStorage.getItem("careeros_token");const response=await fetch(`${resolveApiBaseUrl()}/api/v1/auth/oauth/google/gmail/authorize-url`,{method:"POST",headers:{Authorization:`Bearer ${token}`}});const body=await response.json();if(!response.ok)throw new Error(body.detail||"Unable to start Gmail authorization");window.location.href=body.authorization_url}catch(e:any){setMessage(e.message||"Unable to connect Gmail")}};
  const syncLinkedIn=async()=>{try{await apiClient.post("/api/v1/auth/oauth/linkedin/sync-profile",{});setMessage("LinkedIn profile sync completed.");await load()}catch(e:any){setMessage(e.message||"LinkedIn sync failed")}};
  if(isLoading||loading)return <div className="grid min-h-screen place-items-center bg-background">Loading profile intelligence…</div>; if(!isAuthenticated||!data)return null;
  const score=Number(data.completeness?.overall_score||0); const readiness=data.readiness||{};
  return <CareerOSShell>
    <PageHeader eyebrow="Profile · Intelligence" title="Evidence reconciliation" description="See what CareerOS knows, where it came from and what still needs your confirmation. Extracted facts remain linked to evidence rather than becoming unexplained profile claims." action={<div className="flex gap-2"><Link href="/documents" className="rounded-lg border bg-card px-4 py-2.5 text-sm font-semibold hover:bg-muted">CV & Documents</Link><Link href="/profile" className="rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground">Profile</Link></div>} />
    {message&&<div className="mb-4 rounded-xl border bg-card px-4 py-3 text-sm">{message}</div>}
    <div className="grid gap-4 md:grid-cols-4"><Card><p className="text-xs text-muted-foreground">Profile completeness</p><p className="mt-2 text-3xl font-bold">{score}%</p><div className="mt-3 h-2 rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{width:`${Math.min(score,100)}%`}}/></div></Card><Card><p className="text-xs text-muted-foreground">Vault documents</p><p className="mt-2 text-3xl font-bold">{readiness.documents||0}</p><p className="text-xs text-muted-foreground">{readiness.processed_documents||0} processed</p></Card><Card><p className="text-xs text-muted-foreground">Career evidence</p><p className="mt-2 text-3xl font-bold">{(readiness.experiences||0)+(readiness.skills||0)+(readiness.certifications||0)+(readiness.education||0)}</p><p className="text-xs text-muted-foreground">structured facts</p></Card><Card><p className="text-xs text-muted-foreground">Connections</p><p className="mt-2 text-3xl font-bold">{data.connections?.length||0}</p><p className="text-xs text-muted-foreground">Google / Gmail / LinkedIn</p></Card></div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><Card title="Canonical identity" className="techno-glow"><div className="grid gap-4 sm:grid-cols-2">{[["Name",data.profile?.full_name],["Title",data.profile?.title],["Email",data.profile?.primary_email],["Phone",data.profile?.primary_phone],["Location",data.profile?.location],["LinkedIn",data.profile?.linkedin_url],["Years experience",data.profile?.years_experience],["Reconciliation",data.profile?.reconciliation_status]].map(([label,value])=><div key={label as string} className="rounded-lg border bg-background/25 p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 break-words text-sm font-semibold">{value||"Not available"}</p></div>)}</div></Card><Card title="External connections"><div className="space-y-3">{data.connections?.map((c:any)=><div key={c.id} className="rounded-lg border p-3"><div className="flex items-center justify-between"><p className="font-semibold capitalize">{c.provider}</p><Badge tone="good">Connected</Badge></div><p className="mt-1 text-xs text-muted-foreground">{c.provider_email||"Authorized identity"}</p></div>)}{!data.connections?.length&&<p className="text-sm text-muted-foreground">No external provider connected yet.</p>}<div className="flex flex-wrap gap-2 pt-2"><button onClick={connectGmail} className="rounded-lg border px-3 py-2 text-xs font-semibold hover:bg-muted">Connect Gmail</button><button onClick={syncLinkedIn} className="rounded-lg border px-3 py-2 text-xs font-semibold hover:bg-muted">Sync LinkedIn</button></div></div></Card></div>
    <div className="mt-5 grid gap-5 lg:grid-cols-2"><Card title="Professional experience"><div className="space-y-3">{data.experience?.map((x:any)=><div key={x.id} className="rounded-lg border p-4"><div className="flex justify-between gap-3"><div><p className="font-semibold">{x.title||'Experience'}</p><p className="text-sm text-muted-foreground">{x.company||'Company not available'}</p></div><Badge tone="blue">{x.source_type||'evidence'}</Badge></div></div>)}{!data.experience?.length&&<p className="text-sm text-muted-foreground">Upload a CV or employment evidence to build your timeline.</p>}</div></Card><Card title="Skills & credentials"><div className="flex flex-wrap gap-2">{data.skills?.map((x:any)=><span key={x.id} className="rounded-full bg-muted px-3 py-1.5 text-xs font-medium">{x.name}</span>)}{!data.skills?.length&&<p className="text-sm text-muted-foreground">No skills extracted yet.</p>}</div><div className="mt-4 space-y-2">{data.certifications?.map((x:any)=><div key={x.id} className="rounded-lg border p-3"><p className="text-sm font-semibold">{x.name}</p><p className="text-xs text-muted-foreground">{x.issuer||'Issuer not available'}</p></div>)}</div></Card></div>
    <div className="mt-5"><Card title="Evidence provenance"><p className="mb-4 text-sm text-muted-foreground">Every extraction should remain traceable to the document that produced it.</p>{data.provenance?.length?<div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead><tr className="border-b text-xs text-muted-foreground"><th className="px-2 py-2">Document</th><th className="px-2 py-2">Extraction</th><th className="px-2 py-2">Status</th><th className="px-2 py-2">Confidence</th></tr></thead><tbody>{data.provenance.map((p:any)=><tr key={p.extraction_id} className="border-b last:border-0"><td className="px-2 py-3 font-medium">{p.document||p.document_id||'Unknown'}</td><td className="px-2 py-3 text-xs">{String(p.extraction_id).slice(0,8)}…</td><td className="px-2 py-3">{p.status}</td><td className="px-2 py-3">{p.confidence?.overall!=null?`${Math.round(p.confidence.overall*100)}%`:'—'}</td></tr>)}</tbody></table></div>:<div className="rounded-xl border border-dashed p-8 text-center text-sm text-muted-foreground">No extraction evidence yet.</div>}</Card></div>
  </CareerOSShell>;
}
